name: Release

on:
  release:
    types: [published]

jobs:
  build-sdist:
    name: Build source dist
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - uses: pdm-project/setup-pdm@v4
      with:
        python-version: 3.12
        cache: true
        cache-dependency-path: |
          ./pdm.lock
    - name: Install Dependencies
      run: pdm install
    - name: Build sources
      run: |-
        pdm run pip install build wheel
        python -mbuild -n -s
    - name: Upload sources
      uses: actions/upload-artifact@v4
      with:
        name: dist-sources
        path: dist/*.tar.gz
        retention-days: 2

  build-wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build wheel on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: pip
        python-version: '3.9'
    - name: Set up QEMU
      if: matrix.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16
      with:
        output-dir: dist
      env:
        CIBW_ARCHS_WINDOWS: AMD64
        CIBW_ARCHS_LINUX: x86_64 aarch64
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_TEST_SKIP: '*arm64 *aarch64'
    - name: Upload wheel artifacts
      uses: actions/upload-artifact@v4
      with:
        path: dist/*.whl
        name: dist-wheels-${{matrix.os}}
        retention-days: 2
  publish:
    name: Publish Python package
    needs: [build-sdist, build-wheels]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/tree-sitter-language-pack/
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: dist-*
        merge-multiple: true
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{secrets.PYPI_API_TOKEN}}
